# Generated by manual creation on 2025-10-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_updatetapiruserlogentry_accounts_up_old_val_25b95f_gin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        editable=False,
                        help_text="The API key used for authentication",
                        max_length=64,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for this API key (e.g., 'Mobile App', 'External Service')",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Last used at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this API key is currently active and can be used for authentication",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this API key authenticates as",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]

